apiVersion: v1
kind: Secret
metadata:
  name: {{ include "intelligent-trading-bot.secretName" . }}
type: Opaque
stringData:
  BINANCE_API_KEY: {{ .Values.secrets.BINANCE_API_KEY | quote }}
  BINANCE_API_SECRET: {{ .Values.secrets.BINANCE_API_SECRET | quote }}
  TELEGRAM_BOT_TOKEN: {{ .Values.secrets.TELEGRAM_BOT_TOKEN | quote }}
  TELEGRAM_CHAT_ID: {{ .Values.secrets.TELEGRAM_CHAT_ID | quote }}
